name: Deploy Laravel to AWS Ubuntu

on:
  push:
    branches:
      - main # Triggers deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Run Laravel Commands on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            sudo chown -R www-data:www-data /var/www/html/api-server
            sudo chmod -R 755 /var/www/html/api-server
            sudo chmod -R 775 /var/www/html/api-server/storage
            sudo chmod -R 775 /var/www/html/api-server/bootstrap/cache
